<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="cam_length" value="0.01" />
    <xacro:property name="cam_width" value="0.1" />
    <xacro:property name="cam_height" value="0.05" />
    <xacro:include filename="inertia_calculator.xacro" />

    <link name="camera_link">
        <visual>
            <geometry>
                <box size="${cam_length} ${cam_width} ${cam_height}" />
            </geometry>
            <material name="cam_color">
                <color rgba="0 0 0 1" />
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="${cam_length} ${cam_width} ${cam_height}" />
            </geometry>
        </collision>
        <xacro:box_inertia m="0.1" l="${cam_length}" w="${cam_width}" h="${cam_height}"
                           xyz="0 0 0" rpy="0 0 0" />
    </link>

    <joint name="base_camera_joint" type="fixed">
        <parent link="base_link" />
        <child link="camera_link" />
        <origin xyz="${(base_length + cam_length) / 2.0} 0 ${base_height / 2.0}" rpy="0 0 0" />
    </joint>

    <link name="camera_lens">
    </link>

    <joint name="camera_optical_joint" type="fixed">
        <!-- these values have to be these values otherwise the gazebo camera
            image won't be aligned properly with the frame it is supposedly
            originating from -->
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
        <parent link="camera_link"/>
        <child link="camera_lens"/>
    </joint>

    <gazebo reference="camera_link">
        <material>Gazebo/Red</material>
        <sensor name="camera_sensor" type="camera">
            <pose>0 0 0 0 0 0</pose>
            <visualize>true</visualize>
            <update_rate>10.0</update_rate>
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <frame_name>camera_lens</frame_name>
            </plugin>
        </sensor>
    </gazebo>

</robot>